### ISSUE TITLE
request help: I want to get the upstream response status code。How can I do？

### ISSUE THREAD

**Issue by dingliang5218** [apache/apisix-java-plugin-runner#102]
### Issue description
 I want to get the upstream’s response status-code。How can I do？

public Mono<Void> filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) 

Here，HttpResponse have no any method to get  statuscode or body
 
计划做网关调用展现的功能，希望是获取到代理的上游API的响应状态和响应体入库，并做展现

### Environment

* your apisix-java-plugin-runner version

**Comment by dingliang5218** [comment]
计划做网关调用展现的功能，希望是获取到代理的上游API的响应状态和响应体入库，并做展现

**Comment by tzssangglass** [comment]
This relies on APISIX support for calling the plugin runner in the `header_filter` and `body_filter` phases.

**Comment by jiuchongxiao** [comment]
did you resolved it? @dingliang5218 @tzssangglass

**Comment by tzssangglass** [comment]
> did you resolved it? @dingliang5218 not support yet?@tzssangglass

Not supported yet.
