### ISSUE TITLE
request help: Can request get cookies？

### ISSUE THREAD

**Issue by cws1981** [apache/apisix-java-plugin-runner#109]
### Issue description
Can request get cookies？
### Environment

* your apisix-java-plugin-runner version

**Comment by tzssangglass** [comment]
Yes, this is also part of the nginx variables, using `cookie_*`

**Comment by cws1981** [comment]
> 

I didn’t make it clear, I wanted to ask PluginFilter HttpRequest get cookie😄。
```
@Override
  public Mono<Void> filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) {
     // request.getCookies();
}
```
I have solved it. According to the http protocol, the cookie is in the request header. 
```
String cookie = request.getHeader("cookie");
```
