### ISSUE TITLE
bug:  failed to handle RPC_EXTRA_INFO: unsupported info type: 2 

### ISSUE THREAD

**Issue by Origin-zhao** [apache/apisix-java-plugin-runner#118]
### Issue description

In Java Plugin Runner when   requiredBody return true Not Work 

 ```
    @Override
    public List<String> requiredVars() {
        return null;
    }

    @Override
    public Boolean requiredBody() {
        return Boolean.TRUE;
    }
```

### Environment

- apisix version (cmd: `apisix version`): 2.11
- OS (cmd: `uname -a`): docker
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1. write a java runner
2. config apisix java runner
3. post the url
4. print 503 Service

### Actual result

print ok

### Error log

[error] 66#66: *1511 [lua] init.lua:689: phase_func(): failed to handle RPC_EXTRA_INFO: unsupported info type: 2

**Comment by tzssangglass** [comment]
OK, I checked, it must work well with the latest version of APISIX.

 APISIX v2.12.0 is being released this week, and after it is released, let's modify here: https://github.com/apache/apisix-java-plugin-runner#version-matrix

**Comment by dingliang5218** [comment]
That means java plugin v0.2.0 just works with APISIX v2.12.0 well?

**Comment by tzssangglass** [comment]
> That means java plugin v0.2.0 just works with APISIX v2.12.0 well?

yes

**Comment by limerence-zou** [comment]
I meet the same problem.
when release this week's repair ?  qaq
