### ISSUE TITLE
lua pipe child execvp() failed while executing java

### ISSUE THREAD

**Issue by kennethToyuan** [apache/apisix-java-plugin-runner#119]
2022/01/17 02:16:36 [warn] 44#44: *1689 [lua] init.lua:592: flush conf token lrucache, context: ngx.timer
2022/01/17 02:16:36 [warn] 45#45: *1690 [lua] init.lua:592: flush conf token lrucache, context: ngx.timer
2022/01/17 02:16:39 [warn] 48#48: *44 [lua] init.lua:699: respawning new runner..., context: ngx.timer
2022/01/17 02:16:39 [error] 48#78: lua pipe child execvp() failed while executing java (2: No such file or directory)
2022/01/17 02:16:39 [warn] 48#48: *44 [lua] init.lua:687: runner exited with reason: exit, status: 1, context: ngx.timer
2022/01/17 02:16:39 [warn] 48#48: *44 [lua] init.lua:592: flush conf token lrucache, context: ngx.timer
2022/01/17 02:16:39 [warn] 48#48: *44 [lua] init.lua:697: respawn runner 3 seconds later with cmd: ["java","-jar","-DAPISIX_LISTEN_ADDRESS=unix:\/tmp\/runner.sock","-DAPISIX_CONF_EXPIRE_TIME=3600","\/plugin\/apisix-java-plugin-runner.jar"], context: ngx.timer
2022/01/17 02:16:39 [warn] 44#44: *1803 [lua] init.lua:592: flush conf token lrucache, context: ngx.timer
2022/01/17 02:16:39 [warn] 45#45: *1804 [lua] init.lua:592: flush conf token lrucache, context: ngx.timer

apisix 2.10.0
* your apisix-java-plugin-runner 0.1

部署官方案列到docker容器里出现的问题，

**Comment by weitienwong** [comment]
**同问**
进入容器内部查看，是有`apisix-java-plugin-runner.jar`这个文件的，但是日志里显示` lua pipe child execvp() failed while executing java -jar -Xmx4g -Xms4g /usr/local/apisix/apisix-runner-bin/apisix-java-plugin-runner.jar (2: No such file or directory)`，另外，官方能不能回复及时一点呢

**Comment by tzssangglass** [comment]
> lua pipe child execvp() failed while executing java (2: No such file or directory)

The mistake is in this.

Check the permissions of this file.

> 部署官方案列到docker容器里出现的问题，

Official cases are posted by contributors and are for reference only.

In my experience, there are always similar permission issues with docker.

**Comment by kennethToyuan** [comment]
Error reason: jdk version problem

**Comment by weitienwong** [comment]
> > lua pipe child execvp() failed while executing java (2: No such file or directory)
> 
> The mistake is in this.
> 
> Check the permissions of this file.
> 
> > 部署官方案列到docker容器里出现的问题，
> 
> Official cases are posted by contributors and are for reference only.
> 
> In my experience, there are always similar permission issues with docker.

It still did not work
