### ISSUE TITLE
request help: cannot find conf token and receive undefined filter

### ISSUE THREAD

**Issue by zhangxingdeppon** [apache/apisix-java-plugin-runner#121]
### Issue description
hi team, I met a problem, I developed a filter in `runner-plugin/src/main/java/org/apache/apisix/plugin/runner/filter/`, but the plugin wasn't effective, the error details are:

![image](https://user-images.githubusercontent.com/16789841/150522419-ffee527b-ce86-459d-87c8-2370cc88988d.png)

could you give me some ideas? thank you.
### Environment

* your apisix-java-plugin-runner version
0.2.0

**Comment by zhangxingdeppon** [comment]
it's resolved, because my code error, thanks very much.

**Comment by PhanPirang** [comment]
> it's resolved, because my code error, thanks very much.

I also faced this issue, what's your solution?
