### ISSUE TITLE
request help: failed to receive RPC_HTTP_REQ_CALL: closed

### ISSUE THREAD

**Issue by heshuai-8888** [apache/apisix-java-plugin-runner#122]
### Issue description

There will be exceptions from time to time :  failed to receive RPC_HTTP_REQ_CALL: closed .

![image](https://user-images.githubusercontent.com/57247180/150504737-faff84f5-6439-4efd-917d-7473f2967e4f.png)

What is the reason for this? How to solve?

### Environment

1. Docker deployment;  An apisix-doker image built by myself based on centos7 + apisix ；
2. Upstream uses nacos;
3. Run a Java plugin;

**Comment by tzssangglass** [comment]
open the java runner log for more information, here: https://github.com/apache/apisix-java-plugin-runner/blob/cbd3b3a6ad536df5d1ea71336c4a319a28c0622d/runner-core/src/main/resources/application.properties#L19

BTW, use text instead of images.

**Comment by heshuai-8888** [comment]
logging.level.root=DEBUG   is OPEN 。 
errorinfo :  
2022/02/16 09:59:42 [error] 47#47: *116549586 [lua] init.lua:689: phase_func(): failed to receive RPC_HTTP_REQ_CALL: closed, client: 172.20.255.28, server: _, request: "POST /byd-intergral/in
tergralRule/getIntergralRulePageList HTTP/1.1", host: "172.20.6.10:9080"2022/02/16 09:59:42 [warn] 47#47: *116549586 [lua] plugin.lua:722: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 172.20.255.28, server: _, request: "POST /byd-inte
rgral/intergralRule/getIntergralRulePageList HTTP/1.1", host: "172.20.6.10:9080"

**Comment by heshuai-8888** [comment]
我的运行环境是：
1、自己基于centos 和 apisix 2.11.0 构建的Docker镜像；
2、启动的时候 把java插件jar包 ，挂载到容器里面。
3、上游服务是基于nacos的微服务；
4、路由关联的服务，服务里面配置的插件是：ext-plugin-pre-req 。插件使用Java语言编写。
问题出现的时间点：
当我的上游服务重启后就会偶发的出现这个问题，然后我重启apisix 又能够正常访问；

**Comment by tzssangglass** [comment]
You can keep an eye on whether the container has restarted or whether the java runner process has exited abnormally.

From the information you provided, it's hard for me to determine the problem.
