### ISSUE TITLE
request help: requiredBody return true   503

### ISSUE THREAD

**Issue by navysummer** [apache/apisix-java-plugin-runner#126]
### Issue description
@Override
  public Boolean requiredBody() {
      return true;
  }
![image](https://user-images.githubusercontent.com/17807236/154020635-f809351a-20a7-47a2-997d-abdd08c36070.png)

### Environment

* your apisix-java-plugin-runner version
0.2.0

**Comment by tzssangglass** [comment]
`cannot found token`

1. add reproduction steps
2. use text better then pictures
