### ISSUE TITLE
外置etcd，插件上线后， compacted, will read the configuration again via readdir,

### ISSUE THREAD

**Issue by kennethToyuan** [apache/apisix-java-plugin-runner#127]
### Environment    apisix 2.10.2

* your apisix-java-plugin-runner version 0.2.0
apisix使用的是2.10.2，插件版本是0.2.0
自定义开发插件，上线后，error日志一直输出下图信息

![image](https://user-images.githubusercontent.com/13416357/154182186-4b458828-4137-4658-8d79-fcafce23daa1.png)

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/3438

Don't be panic!
