### ISSUE TITLE
how can i jump to another IP port from Plugin ?

### ISSUE THREAD

**Issue by dingshijie** [apache/apisix-java-plugin-runner#128]
as `the path to the rewrite must start with '/'`
https://github.com/apache/apisix-java-plugin-runner/issues/54

that is to say now we can not jump to another IP port from Plugin ? Except rewrite path , has any other ways jump to another IP port?

**Comment by tzssangglass** [comment]
no way in java runner.

**Comment by tzssangglass** [comment]
The selection of IP and port is implemented in APISIX. I don't know exactly what you mean by jumping.

**Comment by dingshijie** [comment]
> The selection of IP and port is implemented in APISIX. I don't know exactly what you mean by jumping.

rewrite host:port/path in java runner.
now i only can rewrite path，I don't know how to rewrite host in java runner .

**Comment by tzssangglass** [comment]
> rewrite host:port/path in java runner.

not support rewrite host: port in java runner.

> I don't know how to rewrite host in java runner .

you can try ` request.setHeader( "Host", "test.com");` to rewrite the `Host` header.

**Comment by dingshijie** [comment]
> > rewrite host:port/path in java runner.
> 
> not support rewrite host: port in java runner.
> 
> > I don't know how to rewrite host in java runner .
> 
> you can try ` request.setHeader( "Host", "test.com");` to rewrite the `Host` header.

config like this:
{
    "uri": "/graphql",
    "name": "graphql-ext-plugin-pre-req",
    "plugins": {
        "ext-plugin-pre-req": {
            "conf": [{
                "name": "AnalysisRequestFilter",
                "value": "{}"
            }]
        }
    },
    "upstream": {
        "nodes": {
            "10.168.3.15:12:14561": 1
        },
        "type": "roundrobin"
    }
}
when exec AnalysisRequestFilter I want to rewite upstream nodes host,  i don't want to use 10.168.3.15:12:14561.

**Comment by tzssangglass** [comment]
> when exec AnalysisRequestFilter I want to rewite upstream nodes host, i don't want to use 10.168.3.15:12:14561.

As I already said, this is not supported in java runner.

**Comment by dingshijie** [comment]
> > when exec AnalysisRequestFilter I want to rewite upstream nodes host, i don't want to use 10.168.3.15:12:14561.
> 
> As I already said, this is not supported in java runner.

has other ways ? i set a new route like      
"plugins": {
     "proxy-rewrite": {
        "host": "10.168.3.15:12:14561"
    }
}

and i want use ext-plugin-pre-req AnalysisRequestFilter result in the new route rule to do some filter.

**Comment by tzssangglass** [comment]
> and i want use ext-plugin-pre-req AnalysisRequestFilter result in the new route rule to do some filter.

not support yet

**Comment by dingshijie** [comment]
> > and i want use ext-plugin-pre-req AnalysisRequestFilter result in the new route rule to do some filter.
> 
> not support yet

another question : 
doc:  https://apisix.apache.org/zh/docs/apisix/admin-api/#body-%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0
如果不同路由包含相同 uri，根据属性 priority 确定哪个 route 被优先匹配，值越大优先级越高，默认值为 0。

Q:  如果同时匹配到多个route的时候，只会按照优先级最高的route配置执行 还是？

**Comment by tzssangglass** [comment]
> Q: 如果同时匹配到多个route的时候，只会按照优先级最高的route配置执行 还是？

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md

longest prefix match
