### ISSUE TITLE
request help: Filter for hot loading mechanism in pre or post step plugin

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix-java-plugin-runner#129]
### Issue description

We have such a demand to see if it is feasible, and make some enhancements on the current basis. For example, in many scenarios, the authentication logic of the business side of the java technology stack varies from person to person. The platform team provides the business side with an For the hot update scheme of restart, refer to the implementation of zuul groovy filter. When a new authentication service channel is added, provide a dynamic java filter hot update scheme instead of restarting each release. Zuul has been implemented, and we plan to refer to the implementation of zuul. Enhance this logic and want to know if the following solution is feasible.  or some else better way.

### Environment

* your apisix-java-plugin-runner version 0.2.0

**Comment by tzssangglass** [comment]
Dynamic loading filter?
It's possible, I've considered this feature before, but just don't have time to implement it at the moment.

**Comment by xuminwlt** [comment]
Yes，If I do this thing in PR, will it be merged?

**Comment by tzssangglass** [comment]
It is best to send this proposal to the mailing list for discussion first, as a more detailed design is needed.
