### ISSUE TITLE
request help: can't modify request params

### ISSUE THREAD

**Issue by navysummer** [apache/apisix-java-plugin-runner#130]
### Issue description
request.setArg("city","beijing")
There is no change before and after modification
### Environment
jdk11
apisix 2.12.1
* your apisix-java-plugin-runner version
0.2.0

**Comment by tzssangglass** [comment]
Can you provide details of the replication process?
How did you verify that there was no change?
Is it possible to determine that the request went through the filter where you wrote the line of code?

**Comment by navysummer** [comment]
> Can you provide details of the replication process? How did you verify that there was no change? Is it possible to determine that the request went through the filter where you wrote the line of code?

Thinks, I find this problem，Other plugs have modified it
