### ISSUE TITLE
request help: Can I get response body to modify it?

### ISSUE THREAD

**Issue by stray-dog** [apache/apisix-java-plugin-runner#131]
### Issue description
For example:

This is response body: hello world.
I want to get this response body so that I can convert all lowercase h inside to uppercase.

**Comment by tzssangglass** [comment]
not support yet

**Comment by DREZG** [comment]
When will it be supported？

**Comment by tzssangglass** [comment]
> When will it be supported？

I will include this feature support in my plans for the next two months.

**Comment by DREZG** [comment]
If I  get response body to modify it based on the current version, how should I do? how do I modify the source code？
like this:

<img width="475" alt="infoflow 2022-06-06 15-37-59" src="https://user-images.githubusercontent.com/35189605/172117043-7ae600cf-45f6-4766-aafd-29fec5fc10bc.png">

**Comment by tzssangglass** [comment]
> If I get response body to modify it based on the current version, how should I do? how do I modify the source code？

I can't answer that because I haven't thought hard enough about how to achieve it.

**Comment by tzssangglass** [comment]
In fact, APISIX does not currently support getting the response body, but the feature to get the response status and headers is under review.
