### ISSUE TITLE
help request: java-plugin 503error

### ISSUE THREAD

**Issue by rongkang371** [apache/apisix-java-plugin-runner#136]
### Description

java application start error。 
apisix 503 error；
apisix version 2.10.1：[error] 47#47: *2197 [lua] init.lua:618: phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-46.sock: no such file or directory

apsix version 2.12.1: [crit] 14833#14833: *1132 connect() to unix:/usr/local/apisix/conf/conf/apisix-14831.sock failed (2: No such file or directory)

apsix conf:
ext-plugin:
  cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/apisix-runner-bin/apisix-java-plugin-runner.jar']

### Environment

- APISIX version (2.12.1 or 2.10.1):
- Operating system (linux):
- Plugin runner version, for issues related to plugin runners:   Java Plugin Runner-0.2.0

**Comment by tzssangglass** [comment]
docker deployment will have problems with file read and write permissions, please refer to: https://github.com/apache/apisix-java-plugin-runner/issues/61

**Comment by tzssangglass** [comment]
I recommend that you develop in Linux environment.

**Comment by rongkang371** [comment]
i don‘t use docker。 user RPM Offline Package (CentOS 7)。

**Comment by rongkang371** [comment]
> docker deployment will have problems with file read and write permissions, please refer to: #61


i don‘t use docker。 user RPM Offline Package (CentOS 7)。

**Comment by rongkang371** [comment]
solve the problem start apisix in path /usr/local/apisix。why start apisix must in path /usr/local/apisix

**Comment by tzssangglass** [comment]
> solve the problem start apisix in path /usr/local/apisix。why start apisix must in path /usr/local/apisix

`/usr/local/apisix` is default work directory. If you are installing by rpm, do not change this path.
