### ISSUE TITLE
request help: 在服务器上使用 jar包部署报错 

### ISSUE THREAD

**Issue by jianqing1990** [apache/apisix-java-plugin-runner#137]
### Environment

* your apisix-java-plugin-runner version 0.2.0

代码在本地运行调试没有问题，采用 jar包加 ext-plugin: path_for_test: /tmp/runner.sock 运行 没有问题

但是采用ext-plugin:  cmd:['java', '-jar','-Xmx4g','-Xms4g','/home/apisix-runner-bin/apisix-java-plugin-runner.jar'] 部署报错
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
, context: ngx.timer
2022/04/06 17:35:35 [warn] 3196#3196: *44523 [lua] init.lua:798: 2022-04-06 17:35:35.280 ERROR 4114 --- [           main] o.s.b.SpringApplication                  : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.apache.apisix.plugin.runner.PluginRunnerApplication.main(PluginRunnerApplication.java:32) [classes!/:0.2.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [apisix-java-plugin-runner.jar:0.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [apisix-java-plugin-runner.jar:0.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [apisix-java-plugin-runner.jar:0.2.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) [apisix-java-plugin-runner.jar:0.2.0]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory

能帮忙看下是什么问题么

**Comment by tzssangglass** [comment]
pls use English in public chanel;

> Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory

Analysis from the error logs you provided:

> Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory

Maybe the socket file is not found, you can check if `apisix/conf/apisix-xxx.sock` file exists.

**Comment by jianqing1990** [comment]
> pls use English in public chanel;
> 
> > Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory
> 
> Analysis from the error logs you provided:
> 
> > Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory
> 
> Maybe the socket file is not found, you can check if `apisix/conf/apisix-xxx.sock` file exists.

**Comment by jianqing1990** [comment]
sorry I would use English, I had check the file, the file exists, what  should i do ,  delete this file and restart apisix angain?
![微信截图_20220407110945](https://user-images.githubusercontent.com/15780592/162112882-9c61f1c0-3368-4cb3-a291-ae9234d869f7.png)

**Comment by jianqing1990** [comment]
> pls use English in public chanel;
> 
> > Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory
> 
> Analysis from the error logs you provided:
> 
> > Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: No such file or directory
> 
> Maybe the socket file is not found, you can check if `apisix/conf/apisix-xxx.sock` file exists.

I try it today, restart apisix again, the programe create a new apisix-xxxx.sock and it works
![success1](https://user-images.githubusercontent.com/15780592/162134111-e0237caf-e4cf-4ede-8704-9aeb3931bc38.png)
then  i  run apisix quit and restart apisix ,the error report again 
![error](https://user-images.githubusercontent.com/15780592/162134331-10a6927f-25d0-4146-a5d6-78dff5725ce3.png)
what is this problem?

**Comment by tzssangglass** [comment]
> then i run apisix quit and restart apisix ,the error report again

I think it's because `quit` means `stop the apisix server gracefully`, see: https://github.com/apache/apisix/blob/51eec3ea64bba464ab4a6741acc318c502cab26c/apisix/cli/ops.lua#L59

but `ext-plugin` doesn't support exit gracefully, see:https://github.com/apache/apisix/blob/51eec3ea64bba464ab4a6741acc318c502cab26c/apisix/plugins/ext-plugin/init.lua#L847-L849

**Comment by tzssangglass** [comment]
you can just use `stop` or `start` or `restart`.

**Comment by jianqing1990** [comment]
> you can just use `stop` or `start` or `restart`.

I will try what you say, but right now the situation is whatever I try, I can not restart the java plugin success again, even restart the linux server, this java plugin still report error, and apisix could not creat new .sock file
![error](https://user-images.githubusercontent.com/15780592/162171776-beb21d59-bbfd-4805-b348-b62a49ad29a9.png)

**Comment by tzssangglass** [comment]
> My deployment environment is windows 10 wsl, wsl above the running centos, yesterday I started failed, this afternoon I tried the first boot success, like I said above, follow-up until now I have not been able to successfully start the java plugin, I tried to restart wsl to restart the computer, or not

I can't reproduce it, anyway, you can try to clean env var `APISIX_LISTEN_ADDRESS`

**Comment by jianqing1990** [comment]
> > My deployment environment is windows 10 wsl, wsl above the running centos, yesterday I started failed, this afternoon I tried the first boot success, like I said above, follow-up until now I have not been able to successfully start the java plugin, I tried to restart wsl to restart the computer, or not
> 
> I can't reproduce it, anyway, you can try to clean env var `APISIX_LISTEN_ADDRESS`

I'm sorry I didn't directly understand what you said    “you can try to clean env var `APISIX_LISTEN_ADDRESS`”     Could you tell me How should I operate to clean env var `APISIX_LISTEN_ADDRESS`”

**Comment by tzssangglass** [comment]
> Could you tell me How should I operate to clean env var `APISIX_LISTEN_ADDRESS`”

```shell
$ unset APISIX_LISTEN_ADDRESS
```

**Comment by jianqing1990** [comment]
> > Could you tell me How should I operate to clean env var `APISIX_LISTEN_ADDRESS`”
> 
> ```shell
> $ unset APISIX_LISTEN_ADDRESS
> ```

thank you

**Comment by adairll** [comment]
Hello, I have encountered the same problem. Can you share with me how to solve it on your end
