### ISSUE TITLE
init.lua:726: phase_func(): failed to acquire the lock: timeoutrequest help: 

### ISSUE THREAD

**Issue by jiuchongxiao** [apache/apisix-java-plugin-runner#138]
### Issue description
java-plugin demofilter,cannot exec success.

2022/04/20 03:54:56 [error] 44#44: *12875 [lua] init.lua:726: phase_func(): failed to acquire the lock: timeout, client: 10.233.64.0, server: _, request: "GET /test HTTP/1.1", host: "10.27.163.82:8898"
2022/04/20 03:54:56 [warn] 44#44: *12875 [lua] plugin.lua:750: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 10.233.64.0, server: _, request: "GET /test HTTP/1.1", host: "10.27.163.82:8898"
### Environment
![image](https://user-images.githubusercontent.com/13093730/164147546-b975f4b5-6342-4520-a04d-2dc06923178c.png)
# 配置stream
curl "http://10.27.163.82:8897/apisix/admin/upstreams/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '{
"type": "roundrobin","nodes": {"172.24.164.113:8099": 1}}'

#配置路由
curl "http://10.27.163.82:8897/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "uri": "/test",
  "upstream_id": "1",
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "DemoFilter",
          "value": "config"
        }
      ]
    }
  }
}'
* your apisix-java-plugin-runner version
0.2.0

**Comment by jiuchongxiao** [comment]
but the java plugin is run 
![Uploading image.png…]()

**Comment by tzssangglass** [comment]
same as #139
