### ISSUE TITLE
help request: can i use java-plugin-runner to implement proxy_rewrite function

### ISSUE THREAD

**Issue by dchasel** [apache/apisix-java-plugin-runner#141]
### Description

i found apisix is a very powerfull proxy and decide to use it, but lua is tough to our developers, so i degisn to use java-plugin-runner to implement proxy logic, but i found there is no entry for us to modify `upstream_host` in HttpRequest. 

is it possible to provide host rewrite in plugin-runner for developer to set dynamic upstrem_host ?

**Comment by tzssangglass** [comment]
It is not currently supported.
Dynamic upstream settings are not supported by the multilingual plugin.
