### ISSUE TITLE
request help: Get I get the tcp stream in java  plugin?

### ISSUE THREAD

**Issue by langligelang** [apache/apisix-java-plugin-runner#142]
### Issue description
how can I get the tcp stream in java plugin？ like websocket data, mqtt data.
我如何能够获取tcp数据? 比如websocket流，mqtt流。
### Environment

* your apisix-java-plugin-runner version 0.2.0

**Comment by tzssangglass** [comment]
> 我如何能够获取tcp数据? 比如websocket流，mqtt流。

not support, the plugin runner only works at the HTTP level.
