### ISSUE TITLE
bug: setBody not work

### ISSUE THREAD

**Issue by langligelang** [apache/apisix-java-plugin-runner#143]
### Issue description
setBody not work
### Environment

* your apisix-java-plugin-runner version
0.2.0
### Minimal test code / Steps to reproduce the issue

1.  I want to set  Request Body like  request.setBody("h=xxxxxx") or request.setBody("{"hello":"23f"}")
2. But the real server still get the orginal request body.
我想通过setBody设置request body。但是不ok。获取得到的还是原先的request  body。

### What's the actual result? (including assertion message & call stack if applicable)
Get the orginal content
### What's the expected result?
Get the setBody content

**Comment by tzssangglass** [comment]
> Get the orginal content

see: https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#write-filter

```
  @Override
  public Boolean requiredBody() {
      return true;
  }

```

and use

```
String body = request.getBody();
```

in your custom filter.

**Comment by DALKLUNA** [comment]
> (

We meet the same problem, although there is request.setBody() method, but it do not actually work.

In the document, [https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#write-filter](url), the rewrite request is also not mention rewrite body.

**Comment by tzssangglass** [comment]
> We meet the same problem, although there is request.setBody() method, but it do not actually work.
> 
> In the document, [https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#write-filter](url), the rewrite request is also not mention rewrite body.

my mistake, I misread the title.

`setBody` is not currently supported, so it is not written in the documentation.

The `setBody` you see is not for the user, just like some other functions.

But it's a good problem, and in the later refactorings it needs to be marked clearly which functions are open to the user.
