### ISSUE TITLE
request help: build tools add gradle in addition to maven

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix-java-plugin-runner#145]
### Issue description
Build tools using maven only current now, maybe it should support gradle too.
spring-boot uses gradle as the default build tool.  
https://github.com/spring-projects/spring-boot
https://spring.io/blog/2020/06/08/migrating-spring-boot-s-build-to-gradle
### Environment

* your apisix-java-plugin-runner version

**Comment by tzssangglass** [comment]
From a personal perspective, I like to use gradle to build projects. If you would like to contribute this feature, please submit a proposal to dev@apisix.apache.org, and let's discuss it together.

**Comment by qihaiyan** [comment]
> From a personal perspective, I like to use gradle to build projects. If you would like to contribute this feature, please submit a proposal to [dev@apisix.apache.org](mailto:dev@apisix.apache.org), and let's discuss it together.

ok, i have send the mail.
