### ISSUE TITLE
help request: error starting java-plugin-runner directly through apisix

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix-java-plugin-runner#149]
### Current Behavior

apisix version:2.14.1
apisix-java-plugin-runner version:0.2.0
config.yaml:
![image](https://user-images.githubusercontent.com/75060224/174578640-52a4a2dd-b1ff-42cf-9928-8d0067e5d439.png)
![image](https://user-images.githubusercontent.com/75060224/174578882-91b175b4-fe71-47c2-b8b4-67fca7b61cf7.png)

配置好apisix加载java插件参数启动后，发现apisix需要带有进程号的rock文件与runner通信，没有查找到相关配置与解决方法

### Steps to Reproduce

1.准备好插件包
2.配置config.yaml，指定插件启动方式
3.启动apisix

### Environment

apisix version:2.14.1
apisix-java-plugin-runner version:0.2.0

**Comment by wodingyang** [comment]
step1: install apisix-2.14.1 for centos7
step2: prepare the apisix-java-plugin-runner:0.2.0 package
step3: modify confing.yaml: ext-plugin:cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugin/apisix-runner-bin/apisix-java-plugin-runner.jar']
step4: run apisix instance


view error.log:
2022/06/21 08:50:30 [error] 11265#18022: lua pipe child execvp() failed while executing java (2: No such file or directory)


calling a custom java plugin, view error.log:
2022/06/21 08:50:34 [crit] 11261#11261: *3522394 connect() to unix:/usr/local/apisix/conf/apisix-11258.sock failed (2: No such file or directory), client: 192.168.28.12, server: _, request: "POST /hello HTTP/1.1", host: "10.110.3.50:9080"
2022/06/21 08:50:34 [error] 11261#11261: *3522394 [lua] init.lua:841: phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-11258.sock: no such file or directory, client: 192.168.28.12, server: _, request: "POST /hello HTTP/1.1", host: "10.110.3.50:9080"
2022/06/21 08:50:34 [warn] 11261#11261: *3522394 [lua] plugin.lua:750: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 192.168.28.12, server: _, request: "POST /hello HTTP/1.1", host: "10.110.3.50:9080"
















在 2022-06-20 20:37:19，"tzssangglass" ***@***.***> 写道：

发现apisix需要带有进程号的rock文件与runner通信

this socket file was generated by APISIX, no need to created by manual.

I need the complete reproduction of the steps.

Also note, do not use docker to run these.

**Comment by wodingyang** [comment]
1. apisix instance and apisix-java-plugin-runner instance are deployed in the same environment
2.not used docker
3. jdk version = 18
















At 2022-06-21 10:06:37, "tzssangglass" ***@***.***> wrote:

step1: install apisix-2.14.1 for centos7 step2: prepare the apisix-java-plugin-runner:0.2.0 package step3: modify confing.yaml: ext-plugin:cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugin/apisix-runner-bin/apisix-java-plugin-runner.jar'] step4: run apisix instance

It looks like there is no problem with this step.
What needs to be confirmed is.

deploy so that apisix and apisix-java-plugin-runner are deployed in the same environment (don't have one of them deployed in docker)
check the JDK version, >= 11

**Comment by tzssangglass** [comment]
Can you check the permissions of the folder ``/usr/local/apisix/conf/` ` and try to lower the permissions of this folder so that APISIX can write to this folder?

**Comment by wodingyang** [comment]
![image](https://user-images.githubusercontent.com/75060224/174703056-7feb1582-f64e-4915-973a-89c731fad283.png)
the permissions is 777

**Comment by tzssangglass** [comment]
can you try `unset APISIX_LISTEN_ADDRESS`?

and check files under `/usr/local/apisix/conf/`, the PID of `/usr/local/apisix/conf/apisix-{PID}}.sock` should same as `/usr/local/apisix/logs/nginx.pid`

**Comment by wodingyang** [comment]
问题已解决，但是有几个疑惑的地方：
1.前面我一直用systemctl start apisix
            systemctl stop apisix
            systemctl restart apisix
3个命令操作，发现apisix不会调用java-plugin-runner，
改用apisix start操作时发现才会调用

2.不知道在哪里设置APISIX_CONF_EXPIRE_TIME这个参数，发现默认路径是登录用户下的路径，而日志中的路径与默认路径不一致

**Comment by tzssangglass** [comment]
> 1.前面我一直用systemctl start apisix
> systemctl stop apisix
> systemctl restart apisix
> 3个命令操作，发现apisix不会调用java-plugin-runner，
> 改用apisix start操作时发现才会调用

Interesting question, I will look at it when I have time.

> .不知道在哪里设置APISIX_CONF_EXPIRE_TIME这个参数

this value is fixed, `3600`.

**Comment by githubxubin** [comment]
> 问题已解决，但是有几个疑惑的地方： 1.前面我一直用systemctl start apisix systemctl stop apisix systemctl restart apisix 3个命令操作，发现apisix不会调用java-plugin-runner， 改用apisix start操作时发现才会调用
> 
> 2.不知道在哪里设置APISIX_CONF_EXPIRE_TIME这个参数，发现默认路径是登录用户下的路径，而日志中的路径与默认路径不一致

请问是怎么解决的，我也遇到同样的问题 感谢

**Comment by yijieshusheng-git** [comment]
我也遇到了相同的问题，在运行模式下，apisix并没有自动启动自定义插件，也没有生成 xxx.sock文件，我看了下  /usr/local/apisix/conf/这个目录，是有权限新建文件的

**Comment by xiaodizi** [comment]
Same problem in centos 7, I don't know how to solve

**Comment by tomcmd** [comment]
apisix start命令 ，必须在 /usr/local/apisix路径下执行，这样才能生成pid.sock文件！！！！
![image](https://github.com/apache/apisix-java-plugin-runner/assets/9572499/49765b12-744f-44fc-b0f5-e20128af1bae)
