### ISSUE TITLE
help request: 直接通过apisix启动java-plugin-runner出错

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix-java-plugin-runner#151]
### Description

调试运行apisix-java-plugin-runner没有问题后切换到正式启动，配置如下
config.yaml:cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugin/apisix-runner-bin/apisix-java-plugin-runner.jar']
日志中有一行错误：
2022/06/21 08:49:48 [error] 11265#17957: lua pipe child execvp() failed while executing java (2: No such file or directory)
调用自定义的插件，出现如下错误：
2022/06/21 08:50:34 [error] 11261#11261: *3522394 [lua] init.lua:841: phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-11258.sock: no such file or directory, client: 192.168.28.12, server: _, request: "POST /hello HTTP/1.1", host: "10.110.3.50:9080"
2022/06/21 08:50:34 [warn] 11261#11261: *3522394 [lua] plugin.lua:750: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 192.168.28.12, server: _, request: "POST /hello HTTP/1.1", host: "10.110.3.50:9080"
分析日志判断这里apisix与runner通信需要用到带pid的sock文件“apisix-11258.sock”，查看文档并没有发现正式启动的时候如何配置该文件路径，请教如何解决该问题。

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):Linux redis1 3.10.0-693.el7.x86_64 apache/apisix#1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Plugin runner version, for issues related to plugin runners: apisix-java-plugin-version:0.2.0

**Comment by tzssangglass** [comment]
same as #149
