### ISSUE TITLE
request help:  java runner is only support epoll or kqueue

### ISSUE THREAD

**Issue by chenyyyang** [apache/apisix-java-plugin-runner#156]
### Description

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/22273370/176416639-70fada49-d5c1-4f5e-9d46-6d66fc680c4b.png">

M1 的macbook 看来是没法本地debug了吗

### Environment

<img width="232" alt="image" src="https://user-images.githubusercontent.com/22273370/176416088-23bb55cb-400e-4ff9-b488-154a6f7c5409.png">

**Comment by tzssangglass** [comment]
It relies on the `netty-transport-native-kqueue` of the  `aarch_64`, if someday netty provides this jar, then it will be supported.

**Comment by tzssangglass** [comment]
Hi @chenyyyang , if Netty support `netty-transport-native-kqueue` of `aarch_64`, you can try to fix this problem by yourself.

1. include this jar in `pom.xml`
2. update the code you comment on above.

**Comment by chenyyyang** [comment]
@tzssangglass 
As you said, I have tried this steps,but there is something wrong with Netty of JDK libs.

Could you mind kindly give me some advice o this case?

```
 <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <classifier>osx-aarch_64</classifier>
            <version>4.1.78.Final</version>
        </dependency>
 ```
KQueue.isAvailable() still is false at my macbook pro with Apple chip...

the detail messages of the error is shown below:
Possible multiple incompatible native libraries on the classpath for '/var/folders/w5/y1kzc6d148jgxslydddz33_80000gp/T/libnetty_transport_native_kqueue_aarch_6413407257086972134466.dylib'?

**Comment by tzssangglass** [comment]
Unfortunately, I don't have an M1 machine.

BTW, the JDK version should be 11.

**Comment by chenyyyang** [comment]
@tzssangglass  
**Hah, I have solved the above issue via reinstall JDK 11 for X86.**

**Comment by trevzhang** [comment]
Hello, may I ask if the issue has been resolved? I have encountered the same problem as well, where the netty-transport-native-epoll package does not support the Apple M1 chip.

**Comment by chenyyyang** [comment]
You can try to use the JDK for x64 instead  of jdk for arm. This solution  works in my situation ------------------ Original ------------------From: Trevor Zhang ***@***.***>Date: Thu,Feb 22,2024 0:20 PMTo: apache/apisix-java-plugin-runner ***@***.***>Cc: Nathan ***@***.***>, Mention ***@***.***>Subject: Re: [apache/apisix-java-plugin-runner] request help:  java runner isonly support epoll or kqueue (Issue #156)
Hello, may I ask if the issue has been resolved? I have encountered the same problem as well, where the netty-transport-native-epoll package does not support the Apple M1 chip.
