### ISSUE TITLE
request help: Is there any optimizations on this traverse? For instance, getHeader by headerName.

### ISSUE THREAD

**Issue by chenyyyang** [apache/apisix-java-plugin-runner#162]
HttpRequest:166
```
public String getHeader(String headerName) {
        Map<String, String> headers = getHeaders();
        if (!CollectionUtils.isEmpty(headers)) {
            for (Map.Entry<String, String> header : headers.entrySet()) {
                if (header.getKey().equals(headerName)) {
                    return header.getValue();
                }
            }
           return headers.get(headerName);
        }
        return null;
    }
```
Is there any optimizations on this traverse? For instance, getHeader by headerName.

```
 public String getHeader(String headerName) {
        Map<String, String> headers = getHeaders();
        if (!CollectionUtils.isEmpty(headers)) {
           return headers.get(headerName);
        }
        return null;
    }

```
it will be the same I think...

* your apisix-java-plugin-runner version
0.2.0

**Comment by tzssangglass** [comment]
now the origin code is

```
    public String getHeader(String headerName) {
        Map<String, String> headers = getHeaders();
        if (!CollectionUtils.isEmpty(headers)) {
            for (Map.Entry<String, String> header : headers.entrySet()) {
                if (header.getKey().equals(headerName)) {
                    return header.getValue();
                }
            }
        }
        return null;
    }
```

I think this change is not very meaningful.

**Comment by chenyyyang** [comment]
```
 public String getHeader(String headerName) {
        Map<String, String> headers = getHeaders();
        if (!CollectionUtils.isEmpty(headers)) {
           return headers.get(headerName);
        }
        return null;
    }

```

This way to get value may faster due to O(1) time complexity,
instead of foreach  O(n)  time complexity...

@tzssangglass 
BTW.Do you mind sharing more information of How to participate in the development of this project? 
Maybe I can take some tasks .
Really be interested on Apisix

**Comment by tzssangglass** [comment]
> BTW.Do you mind sharing more information of How to participate in the development of this project?

https://www.apiseven.com/blog/use-Java-to-write-Apache-APISIX-plugins, I hope this helps you.

> This way to get value from header may be faster due to O(1) time complexity,
> instead of foreach  O(n)  time complexity

Usually there will not be many headers, so the optimization here does not seem necessary. entrySet is only theoretically O(n), not practically.
