### ISSUE TITLE
help request: Java Plugin Runner thorws warning

### ISSUE THREAD

**Issue by MorganArthur** [apache/apisix-java-plugin-runner#165]
### Description

开发java版的外部程序遇到的问题：

程序：apisix是在win11上通过docker-compose安装的容器部署的

java外部插件是clone的demo项目进行改造的

![image](https://user-images.githubusercontent.com/24489342/178892037-cb950d32-2246-4882-b2f4-dcc6ad190c38.png)
![image](https://user-images.githubusercontent.com/24489342/178892054-18c42f54-0021-4690-82dd-a6c2c7249a74.png)

根据文档描述的，我将外部插件编译好的jar可执行文件，上传到了apisix的容器内部
![image](https://user-images.githubusercontent.com/24489342/178892217-8f4c7c2c-f7ab-4a00-b486-2fa05166c212.png)

之后修改了配置文件并重启了apisix
![image](https://user-images.githubusercontent.com/24489342/178892322-03d7af62-52da-4453-a67a-267dc5f887b5.png)

然后在Dashboard配置路由信息
![image](https://user-images.githubusercontent.com/24489342/178892381-ac49b8b9-3264-478a-a1a7-8b3eaf5577b7.png)

测试路由转发报错
![image](https://user-images.githubusercontent.com/24489342/178892438-fef6339e-73ec-4990-97e4-f6cf47a2220e.png)
错误日志是这些
![image](https://user-images.githubusercontent.com/24489342/178892522-6f103868-3a85-4967-a58c-f89c1f3da927.png)

我不知道是哪一步出了问题，麻烦可以帮忙处理一下吗

### Environment

- APISIX version (run `apisix version`):2.13-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by MorganArthur** [comment]
2022/07/14 05:46:45 [warn] 58#58: *257 [lua] init.lua:931: respawning new runner..., context: ngx.timer
2022/07/14 05:46:45 [error] 58#2945: lua pipe child execvp() failed while executing java (2: No such file or directory)
2022/07/14 05:46:45 [warn] 58#58: *257 [lua] init.lua:919: runner exited with reason: exit, status: 1, context: ngx.timer
2022/07/14 05:46:45 [warn] 58#58: *257 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 58#58: *257 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 58#58: *257 [lua] init.lua:929: respawn runner 3 seconds later with cmd: ["java","-jar","-Xmx1g","-Xms1g","\/usr\/local\/apisix\/external_plugin\/apisix-java-plugin-runner.jar"], context: ngx.timer
2022/07/14 05:46:45 [warn] 49#49: *1467811 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 49#49: *1467811 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 51#51: *1467812 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 51#51: *1467812 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 46#46: *1467813 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 54#54: *1467814 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 46#46: *1467813 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 54#54: *1467814 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 45#45: *1467815 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 45#45: *1467815 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 44#44: *1467816 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 53#53: *1467817 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 44#44: *1467816 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 52#52: *1467818 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 53#53: *1467817 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 52#52: *1467818 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 55#55: *1467823 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 50#50: *1467824 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 50#50: *1467824 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 55#55: *1467823 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 47#47: *1467825 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 47#47: *1467825 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer
2022/07/14 05:46:45 [warn] 48#48: *1467826 [lua] init.lua:361: flush_token(): flush conf token in shared dict, context: ngx.timer
2022/07/14 05:46:45 [warn] 48#48: *1467826 [lua] init.lua:818: flush conf token lrucache, context: ngx.timer

**Comment by tzssangglass** [comment]
> 2022/07/14 05:46:45 [error] 58#2945: lua pipe child execvp() failed while executing java (2: No such file or directory)

APISIX cannot find the jar file path, please check the file path inside docker and whether APISIX has permission to read and write the jar file.

**Comment by MorganArthur** [comment]
![image](https://user-images.githubusercontent.com/24489342/179157093-97e40e4a-a62f-4677-9c62-c62ddd765580.png)

我执行了 chmod 777，restart container again，all the same this error

**Comment by tzssangglass** [comment]
It looks like you wrote the wrong path.

where `apisix-java-plugin-runner.jar`? `/usr/local/apisix-plugin-runner` or `/usr/local/apisix/external_plugin`?

**Comment by MorganArthur** [comment]
/usr/local/apisix-plugin-runner this path is configured by me today，/usr/local/apisix/external_plugin this path was configured by me yesterday. I repackaged the image and configured it again

![image](https://user-images.githubusercontent.com/24489342/179168443-c353253b-6bae-4d6e-935f-a598ca944931.png)

**Comment by MorganArthur** [comment]
I tried it. I put the plugin runner and apimix together to create a new apimix image. There is no problem deploying and using external plug-ins.

However, for apifix image, my external plug-ins may change frequently. What I hope is that apifix does not need to re mirror, but only needs to modify the executable package of the external plug-ins.

I thought of a way to mount the directory of external plug-ins to the outside of the container, and then update the executable package of external plug-ins in this mounted directory. I don't know whether this method is feasible?

**Comment by MorganArthur** [comment]
After experiments, I came to a conclusion that I need to create an apifix image containing plugin runner first, then start the image container, and then modify and upload the executable package of plugin runner.

However, this situation is not explained in the document, or I did not find the corresponding document information. I think in the development process, we don't know that we need to develop external plug-ins independently from the beginning, but we will consider developing external plug-ins only when we find that some requirements are not met in the process of using apifix.

Therefore, we first deployed an image container that does not contain plugin runner. Later, when we need to develop external plug-ins, we only need to upload the developed plugin runner to the APIs IX container to use it directly.

I hope the external plug-in development process should be like this. Although repacking the image and starting the container is not a very complicated work, I think it can be saved

**Comment by tzssangglass** [comment]
From the community feedback, it appears that the re-build image deployment method also exists. ref docs: https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/zh/quick-start.md#%E9%83%A8%E7%BD%B2

**Comment by MorganArthur** [comment]
Yes, I mean, the problem I found out was that when I first started using the official Apisix image, if I wanted to use plugin-Runner, I had to rebuild an image that included plugin-Runner before I could use the external plug-in, instead of what the documentation said, Only deploy in the same container. This is not reflected in the documentation.

![image](https://user-images.githubusercontent.com/24489342/179431099-3e14b859-9230-443d-bb89-737cc856742f.png)

Then, I would like to say that, as mentioned in the documentation, to use plugin-runner, only plugin-runner and Apisix need to be in the same container, so that developers only need to focus on the development of plugin-runner. Plugin-runner's executable package is provided, and there is no need to pay attention to whether plugin-Runner and Apisix have rebuilt the new image

**Comment by tzssangglass** [comment]
> Plugin-runner's executable package is provided, and there is no need to pay attention to whether plugin-Runner and Apisix have rebuilt the new image

Would you like to send this topic to the mailing list on dev@apisix.apache.org for discussion about providing an APISIX image with the plugin runnner. (Since this issue is not unique to java runner, plugin runners such as go also do not have mirrors)

**Comment by MorganArthur** [comment]
好的

**Comment by lefreet** [comment]
@MorganArthur is there any solution from the apisix ?

**Comment by tomcmd** [comment]
apisix start命令 ，必须在 /usr/local/apisix路径下执行，这样才能生成pid.sock文件！！！！
![image](https://github.com/apache/apisix-java-plugin-runner/assets/9572499/49765b12-744f-44fc-b0f5-e20128af1bae)
