### ISSUE TITLE
bug: request设置新的body替换客户端原请求body无效

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix-java-plugin-runner#172]
### Issue description
在插件中将客户端发送的body内容替换成新的body无效，后端接受的还是客户端内容
### Environment
* your apisix-java-plugin-runner version
0.2.0

<dependency>
	<groupId>io.github.ericluoliu</groupId>
	<artifactId>apisix-runner-core</artifactId>
	<version>0.5.0</version>
</dependency>
### Minimal test code / Steps to reproduce the issue

1.客户端发送原始请求，body内容如下:
![image](https://user-images.githubusercontent.com/75060224/181190903-a036b444-88a3-43a1-ad4c-f93bc16240d6.png)
2.apisix命中路由后调用java插件，修改body内容
![image](https://user-images.githubusercontent.com/75060224/181191082-76c4a99a-14cf-4ab0-a6e8-8a70a28069c3.png)
![image](https://user-images.githubusercontent.com/75060224/181191122-cc64a494-b0a1-42b0-add4-1533a2b552c5.png)
3.查看上游接收到的请求，body内容为客户端发送的原始数据，插件没有替换成功
![image](https://user-images.githubusercontent.com/75060224/181191247-ea3c84d9-fd85-418f-9a82-952e41a9af07.png)

### What's the actual result? (including assertion message & call stack if applicable)
日志打印：请求体------------>aaa
### What's the expected result?
日志打印：请求体------------>abcdefghijklmnopqrstuvwxyz

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix-java-plugin-runner/issues/143#issuecomment-1127353544
