### ISSUE TITLE
request help: 如何获取consumer_name或者设置consumer

### ISSUE THREAD

**Issue by dargoner** [apache/apisix-java-plugin-runner#173]
### Issue description

请问如何在 filter 方法中获取consumer_name或者设置consumer_name到 ctx

lua版有 consumer_mod.attach_consumer(ctx, consumer, consumer_conf),但是 Java插件好像没提供

### Environment

* your apisix-java-plugin-runner 0.2-master

**Comment by tzssangglass** [comment]
`consumer_name ` is var in APISIX, so you can use 

```
  @Override
  public List<String> requiredVars() {
      List<String> vars = new ArrayList<>();
      vars.add("consumer_name");
      return vars;
  }
```

ref: https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#the-functions-must-be-implemented-of-filter-execution
