### ISSUE TITLE
request help: log4j日志会在error.log里面重复输出

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix-java-plugin-runner#175]
### Issue description
在java plugin runner使用了log4j打印日志信息到单独的日志文件中，但是发现nginx还是会将信息内容输出到error.log中。请问有配置避免这样的重复输出么(非调整日志级别的方式)？
### Environment

* your apisix-java-plugin-runner version 0.5.0

**Comment by tzssangglass** [comment]
same as: https://github.com/apache/apisix-java-plugin-runner/issues/22

No way has been worked out yet.

**Comment by wodingyang** [comment]
thank you
