### ISSUE TITLE
request help: 插件间如何传递变量

### ISSUE THREAD

**Issue by dargoner** [apache/apisix-java-plugin-runner#178]
### Issue description

比如Java plugin第一个插件filter中设置新 Header，但是顺序执行的第二插件，filter取不到第一个插件设置的Header,请问如何在插件间如何传递变量

### Environment

* your apisix-java-plugin-runner version 0.2

**Comment by tzssangglass** [comment]
Maybe you can create some containers to store it. At the moment I don't know how to implement.
