### ISSUE TITLE
feat: add apisix call to terminate plugin runner

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-java-plugin-runner#18]
right now apisix just starts the plugin runner, but there is no support for stopping the plugin runner, which means that when apisix is stopped, the plugin runner will still be running. I don't think this makes sense, because the plugin runner lifecycle starts and should end with apisix.

**Comment by tzssangglass** [comment]
cc @spacewander @dmsolr

**Comment by spacewander** [comment]
I just try it with the Go Plugin runner and it will be terminated when APISIX stops.

**Comment by tzssangglass** [comment]
ok, I will try to implement this logic later.

**Comment by spacewander** [comment]
You don't need to implement it. The runner must be terminated when APISIX stops.

> The sub-process will be killed via SIGKILL if it is still alive when the instance is collected by the garbage collector.

https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/pipe.md#spawn

**Comment by tzssangglass** [comment]
so the cmd command should add nohup?

the original cmd I had in mind was
```yaml
ext-plugin:
  cmd: nohup java -jar /root/IdeaProjects/apisix-java-plugin-runner-1/dist/apisix-runner-bin/apisix-java-plugin-runner.jar > logs/java_runner.log 2>&1 &
```

now I changed it to this

```yaml
ext-plugin:
  cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/root/IdeaProjects/apisix-java-plugin-runner-1/dist/apisix-runner-bin/apisix-java-plugin-runner.jar']
```

and there is no need to provide startup.sh for APISIX to execute.

**Comment by spacewander** [comment]
Yes, there is no need to add nohup as the command should not be run as a daemon.
