### ISSUE TITLE
request help: receive undefined filter

### ISSUE THREAD

**Issue by PhanPirang** [apache/apisix-java-plugin-runner#186]
### Issue description
I got "receive undefined filter: TokenValidator, skip it" message.
In Java, my plugin's name is "TokenValidator"

### Environment
Ubuntu 20.04

* apisix-java-plugin-runner version
0.3.0

![111](https://user-images.githubusercontent.com/12493118/184793294-dd7417e1-0ab6-4a12-b8d4-64de8c330bfd.PNG)

**Comment by PhanPirang** [comment]
It seems that in "apisix-runner-plugin" module is missing in "apisix-runner-starter" pom.xml.

**Comment by tzssangglass** [comment]
> It seems that in "apisix-runner-plugin" module is missing in "apisix-runner-starter" pom.xml.

yes, The new version is now in distribution, and the new version will use a new way to build, ref: https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/installation-guide.md

now `0.3.0-SNAHSHOT` is available.

**Comment by PhanPirang** [comment]
Great!

**Comment by ennian001** [comment]
Alternatively, you can place the plugin in the same directory as the Spring Boot main class.
![image](https://github.com/apache/apisix-java-plugin-runner/assets/36769491/3794c015-b7e5-4e1f-ac7b-81a9c42baeeb)
