### ISSUE TITLE
request help: Could not find artifact org.apache.apisix:apisix-plugin-runner:pom:0.3.0

### ISSUE THREAD

**Issue by PhanPirang** [apache/apisix-java-plugin-runner#190]
### Issue description
After I included runner-starter dependency
<dependency>
	<groupId>org.apache.apisix</groupId>
	<artifactId>apisix-runner-starter</artifactId>
	<version>0.3.0</version>
</dependency>

I got the below issue:
Could not find artifact org.apache.apisix:apisix-plugin-runner:pom:0.3.0 in central (https://repo.maven.apache.org/maven2)

### Environment
Windows

*apisix-java-plugin-runner version 0.3.0

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix-java-plugin-runner/issues/188

link: https://repo.maven.apache.org/maven2/org/apache/apisix/apisix-runner-core/0.3.0/

**Comment by tzssangglass** [comment]
I loaded this dependency in a completely new environment, and it worked. ref: https://github.com/tzssangglass/java-plugin-runner-demo-1

**Comment by yuqiquan** [comment]
问一下，这个问题解决了吗。我已经尝试很多次了，使用一个全新的maven 始终出现
Could not find artifact org.apache.apisix:apisix-plugin-runner:pom:0.3.0 in central

**Comment by tzssangglass** [comment]
> 问一下，这个问题解决了吗。我已经尝试很多次了，使用一个全新的maven 始终出现
> Could not find artifact org.apache.apisix:apisix-plugin-runner:pom:0.3.0 in central

did you add [repo.maven.apache.org/maven2](https://repo.maven.apache.org/maven2) to your local maven center config?

I tried in a new environment and it downloaded fine

**Comment by PhanPirang** [comment]
> I loaded this dependency in a completely new environment, and it worked. ref: https://github.com/tzssangglass/java-plugin-runner-demo-1

I clone this repo too, but it doesn't work too. The same issue.

**Comment by PhanPirang** [comment]
![image](https://user-images.githubusercontent.com/12493118/186820661-16a7c80a-57b7-4def-955d-b55f598f5bd8.png)

It seems that below dependency doesn't exist
org.apache.apisix:apisix-runner-starter:jar:0.3.0

**Comment by yuqiquan** [comment]
> 

我添加了这个到我的maven配置中，但依然无效

**Comment by sunhao-java** [comment]
He's working on the problem, please be a moment!

**Comment by tzssangglass** [comment]
OK, the released version 0.3.0 was not fully released, I re-released it again. If I can not repeat the RELEASE version, I will re-release version 0.3.1.

Now 0.3.1-SNAPSHOT is available. ref: https://github.com/tzssangglass/java-plugin-runner-demo-1/tree/0.3.1-SNAOSHOT

**Comment by tzssangglass** [comment]
`apisix-plugin-runner` has released: https://repo.maven.apache.org/maven2/org/apache/apisix/

try again

**Comment by sunhao-java** [comment]
It seems to be back to normal and I have been able to download the dependency normally.
