### ISSUE TITLE
request help: receive undefined filter: xxxx, skip it

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix-java-plugin-runner#199]
### Issue description
**custom filter is not applied.** 
error.log is as below picture.
![스크린샷 2022-10-07 오후 1 03 40](https://user-images.githubusercontent.com/79562672/194465780-067b8f3e-fb82-4542-adca-c85dfdab9476.png)

I am trying to deploy to vm using apisix-docker + apisix-java-plugin-runner.
This was done with reference to the below.
1) https://apisix.apache.org/docs/apisix/2.15/getting-started/
2) https://github.com/apache/apisix-java-plugin-runner/blob/release/0.3.0/docs/zh/quick-start.md

-Detail step-
1. (ubuntu) git clone -b release/apisix-2.15.0 https://github.com/apache/apisix-docker.git
2. (local) git clone -b release/0.3.0 https://github.com/apache/apisix-java-plugin-runner.git
3. write custom plugins in local(macos)
![스크린샷 2022-10-07 오후 1 30 36](https://user-images.githubusercontent.com/79562672/194468533-9b5306bc-ccaa-4f17-8425-877d276ccf21.png)
4. (local) cd /apache/apisix-java-plugin-runner-release-0.3.0' and './mvnw package
5. (local) cd dist and Add Dockerfile
<img width="822" alt="스크린샷 2022-10-07 오후 1 40 18" src="https://user-images.githubusercontent.com/79562672/194470707-ad75b869-195a-40b8-a92a-60af5ceb6c18.png">

6. Transfer the dist folder(apache-apisix-java-plugin-runner-0.3.0-bin.tar.gz, Dockerfile) to ubuntu
7. (ubuntu) cd dist and docker build -t apache/apisix:2.15.0-alpine-with-java-plugin .
8. (ubuntu) Change the apisix image in docker-compose.yml
<img width="394" alt="스크린샷 2022-10-07 오후 1 49 49" src="https://user-images.githubusercontent.com/79562672/194470063-0288a0d8-3f92-4feb-b915-a19053ce6f4c.png">

9. (ubuntu) add the configure in config.yaml file
<img width="740" alt="스크린샷 2022-10-07 오후 1 58 46" src="https://user-images.githubusercontent.com/79562672/194471338-8556d726-671a-448e-9f00-10b7070f410a.png">

10. (ubuntu) chmod 777 -R example
11. (ubuntu) cd example and docker-compose up -d
12. (ubuntu) create route and upstream
`curl "http://127.0.0.1:9080/apisix/admin/upstreams/99" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "10.70.190.49:80": 1
  }
}'`
`curl "http://127.0.0.1:9080/apisix/admin/routes/99" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "uri": "/managesnsdata/*",
  "upstream_id": "99",
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "DemoFilter",
          "value":"{\"validate_header\":\"token\",\"rejected_code\":\"403\"}"               
        }
      ]
    }
  }
}'`

13. and then curl is called(with/without header value), the custom filter(DemoFilter) is not applied and it responds normally.

How can i apply a filter?
plz, review my step and solve this problem...
Thank you in advance
@tzssangglass

### Environment
apisix-docker release/apisix-2.15.0
apisix-java-plugin-runner  release/0.3.0
(local, ubuntu) JDK 11
local is macos
Ubuntu 20.04.3 LTS

**Comment by tzssangglass** [comment]
If you are starting the source code directly and putting filters in the `runner-plugin`, you need to change `            <artifactId>apisix-runner-plugin-sdk</artifactId>
` to `<artifactId>apisix-runner-plugin</artifactId>` in the pom.xml of the `runner-core`

**Comment by tzssangglass** [comment]
try with 

```shell
sed -i 's/apisix-runner-plugin-sdk/apisix-runner-plugin/' runner-core/pom.xml
```

**Comment by Cheol-Soon-Choi** [comment]
d

**Comment by Cheol-Soon-Choi** [comment]
> try with
> 
> ```shell
> sed -i 's/apisix-runner-plugin-sdk/apisix-runner-plugin/' runner-core/pom.xml
> ```

@tzssangglass 
thanks for the answer, but i'm still a beginner. 
do you mean that change to `sed -i 's/apisix-runner-plugin-sdk/apisix-runner-plugin/'` instead of second line in dockerfile of step5?

or

```
RUN sed -i "s/dl-cdn.alpinelinux/org/mirrors.aliyun.com/g" /etc/apk/repositories && sed -i 's/apisix-runner-plugin-sdk/apisix-runner-plugin/' && apk add --no-cache openjdk11-jre
```

sorry, i can't understand...

**Comment by tzssangglass** [comment]
https://github.com/apache/apisix-java-plugin-runner/blob/d5421c292ef0d0ea93fb484afef668d7e2fc8767/runner-core/pom.xml#L38

I mean turn `<artifactId>apisix-runner-plugin-sdk</artifactId> ` here into `<artifactId>apisix-runner-plugin</artifactId>`

why? Because you do: 

> * (local) git clone -b release/0.3.0 [apache/apisix-java-plugin-runner.git](https://github.com/apache/apisix-java-plugin-runner.git)

and you put your DemoFilter into `runner-plugin`.

After you have done with turned `<artifactId>apisix-runner-plugin-sdk</artifactId>` here into `<artifactId>apisix-runner-plugin</artifactId>`,  the jar that generated by `./mvnw package` would contain `runner-plugin`(include your DemoFilter).

> And, is my step a general way to use apisix and java runner together? It cannot be clearly identified and understood with the current reference documentation...

There is some documentation(ref: https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/installation-guide.md), but it's not newbie friendly enough. I'm going to spend time refactoring the documentation.

**Comment by Cheol-Soon-Choi** [comment]
Thanks for your help. I will change dependency according to your advice.

And i've already read the installation reference. It was easy to follow(1. create spring boot ~ 6. implementing filter). But I didn't know what to do after that(my question is == how do i combine it with apisix? can i just run the boot image? etc...) That's why I couldn't solve the above question, so I asked if my step is a general method.
I want to understand and learn about this.

**Comment by yijieshusheng-git** [comment]
> read the installation reference. It was easy to follow(1. create spring boot ~ 6. implementing filter). But I didn't know what to do after that(my question is == how do i combine

hello,Have you solved this problem? How was it resolved?  thanks!

**Comment by yijieshusheng-git** [comment]
> hello,Have you solved this problem? How was it resolved? thanks!
