### ISSUE TITLE
request help: Custom filter performed twice?

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix-java-plugin-runner#205]
### Issue description
one request, but custom filter performed twice.
my flow is :
request > apisix + apisix runner(include custom filter) > my Backend Service A > my Backend Service B.
and Service A redirect to service B.
in this case, Is it normal for custom filters to work twice? (i guess that's right...)

I want the custom filter to work once regardless of the redirect(1 request ->  custom filter work once ->  1 response)
What should I do ??

Thank you in advance
@tzssangglass

### Environment
ubuntu

* your apisix-java-plugin-runner version 0.3.0

**Comment by tzssangglass** [comment]
how did you config route?

**Comment by Cheol-Soon-Choi** [comment]
my route is,
`{
  "uri": "/*",
  "name": "test",
  "methods": [
    "GET"
  ],
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "HiFilter",
          "value": "{\"apiCode\":\"apiCode\",\"rejected_code\":\"403\"}"
        }
      ]
    }
  },
  "upstream_id": "99",
  "status": 1
}`

my backend, (serviceA = test2(), serviceB = test() method)
<img width="594" alt="스크린샷 2022-10-20 오후 2 35 26" src="https://user-images.githubusercontent.com/79562672/196864729-1e01f6e3-aade-492b-a66b-9df6f1b35f91.png">

my custom filter,
![스크린샷 2022-10-20 오후 2 37 39](https://user-images.githubusercontent.com/79562672/196864916-9714de8c-f6a8-4c17-a470-15fabaaec1d5.png)

my error log,
![스크린샷 2022-10-20 오후 2 39 05](https://user-images.githubusercontent.com/79562672/196865083-34cc0238-50ab-4ee7-8717-bdb7347430d0.png)

Please refer to the above.
thanks, @tzssangglass

**Comment by tzssangglass** [comment]
When you request APISIX once, output `TWICE?` twice?

**Comment by Cheol-Soon-Choi** [comment]
> When you request APISIX once, output `TWICE?` twice?

yes.. Need more information? Redirect doesn't seem to matter.

**Comment by tzssangglass** [comment]
> request > apisix + apisix runner(include custom filter) > my Backend Service A > my Backend Service B.
> and Service A redirect to service B.

can you provide more info about this?

**Comment by Cheol-Soon-Choi** [comment]
Since the url is /* in my router settings, the custom filter works once in the /test2 call, and the custom filter works once more in the redirected /test call, so is it logged twice in total??

**Comment by Cheol-Soon-Choi** [comment]
Solved the problem. It happened because the router was set to duplicate.
I'm sorry I'm not used to it. @tzssangglass 

Additionally,
When I call apisix gw using resttemplate, the returned result is fine, but the custom filter doesn't seem to work.
on the other way, When i call apisix gw directly, the custom filter works fine.
Is there anything I missed in this process?

**Comment by tzssangglass** [comment]
> Since the url is /* in my router settings, the custom filter works once in the /test2 call, and the custom filter works once more in the redirected /test call, so is it logged twice in total??

If you are saying that a redirect request occurred on the client side, then yes, APISIX processed the request twice and the java plugin runner will also process it twice.

**Comment by tzssangglass** [comment]
> Additionally,
> When I call apisix gw using resttemplate, the returned result is fine, but the custom filter doesn't seem to work.
> on the other way, When i call apisix gw directly, the custom filter works fine.

It looks like the resttemplate sends a different request than the one sent by the direct call.
