### ISSUE TITLE
request help: apisix-java-plugin-runner 构建之后没找到新增的代码 部署也不生效

### ISSUE THREAD

**Issue by 18211927120** [apache/apisix-java-plugin-runner#209]
### Issue description
apisix-java-plugin-runner 构建之后没找到新增的代码 部署也不生效

### Environment

* your apisix-java-plugin-runner version

**Comment by tzssangglass** [comment]
follow https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/deployment-guide.md ?

**Comment by 18211927120** [comment]
好的 我看下 按照网上的教程是直接写在runner-plugin这个模块中的 
![image](https://user-images.githubusercontent.com/57982877/199424680-661b3c5b-1def-495d-9af3-6e78c7a56070.png)
我现在试下这种方式
