### ISSUE TITLE
request help: rewrite request body

### ISSUE THREAD

**Issue by kamyam** [apache/apisix-java-plugin-runner#222]
### Issue description
怎么样才可以修改请求参数的报文？
request.setBody()，不起作用，如果用lua是怎么实现

### Environment

* your apisix-java-plugin-runner version

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix-java-plugin-runner/issues/143#issuecomment-1127353544

**Comment by tzssangglass** [comment]
> 那lua插件支持重写RequestBody吗,有没有DEMO参考

search `ngx.req.set_body_data` in APISIX's source code
