### ISSUE TITLE
request help: PostRequest 如何获取 HttpRequest 请求头中的信息? 

### ISSUE THREAD

**Issue by 15003476628** [apache/apisix-java-plugin-runner#230]
### Environment

* your apisix-java-plugin-runner version 0.4  

说明:
    首先在apisix-dashboard上面配置了2个插件, 分别是 ext-plugin-pre-req 和ext-plugin-post-resp !
   对应的的 java-plugin 分别名称分别 demo1 和 demo2,
   在插件demo1 的filter 方法中, 会处理逻辑, 并且把用户信息发在 请求头中, request.setHeader("userInfo","用户信息");

现在需要在 demo2 中根据用户信息,处理 响应体信息
但是如何才能 在

 public void postFilter(PostRequest request, PostResponse response, PluginFilterChain chain){
}
这个方法中获取用户信息?

**Comment by soulbird** [comment]
same as #231
