### ISSUE TITLE
help request: ext-plugin-post-resp 如何把请求中的自定义请求头传递给第三方插件?

### ISSUE THREAD

**Issue by 15003476628** [apache/apisix-java-plugin-runner#231]
### Description

业务要求:
   请求头中 自定义了一个字段, user ,需要根据用户信息 修改响应体

使用的是java插件, user 这个字段如何传递给 java-plugin-run?

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Try `request.getVars(http_user)`

**Comment by 15003476628** [comment]
> request.getVars(http_user)  只能获取到 nginx的默认变量请求头,例如:server_port  
但是不能获取到自定义的请求头信息!

**Comment by soulbird** [comment]
see: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_

**Comment by 15003476628** [comment]
> see: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_

这里面都是nginx的内置变量    没有找到我需要的!

**Comment by soulbird** [comment]
> > see: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_
> 
> 这里面都是nginx的内置变量 没有找到我需要的!

$http_user

**Comment by 15003476628** [comment]
> > > see: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_
> > 
> > 
> > 这里面都是nginx的内置变量 没有找到我需要的!
> 
> $http_user

非常感谢,非常感谢! 已获取到了

**Comment by xiaolajiyhy** [comment]
请问是怎么获取到的
