### ISSUE TITLE
bug: 0.0.4一个jar包,19MB,你要不要看看你们到底打包进去了什么?

### ISSUE THREAD

**Issue by davidricardo1026** [apache/apisix-java-plugin-runner#266]
搞不懂,一个jar,19MB,这是要搞什么的节奏,这边有相关java的开发人员吗?

**Comment by tzssangglass** [comment]
where is the 19M jar package did you found?

you can found this the release jar package on: https://repo1.maven.org/maven2/org/apache/apisix/apisix-runner-core/0.4.0/

**Comment by monkeyDluffy6017** [comment]
considered resolved
