### ISSUE TITLE
bug: 自定义了一个日志记录的java插件，但是在插件启动之后，发现有日志重复打印的问题

### ISSUE THREAD

**Issue by hq0819** [apache/apisix-java-plugin-runner#278]
#### 插件代码
![image](https://github.com/apache/apisix-java-plugin-runner/assets/52909899/6fe37410-1752-48f6-a24c-31349fac4809)
#### apisix插件配置
![image](https://github.com/apache/apisix-java-plugin-runner/assets/52909899/187261c7-51aa-4bc0-acbd-907be55df863)
启动之后
![image](https://github.com/apache/apisix-java-plugin-runner/assets/52909899/7a178ed4-2f37-4958-8fd1-391379a57e44)

是我哪里出问题了吗？

**Comment by hq0819** [comment]
日志配置错了 = =

**Comment by monkeyDluffy6017** [comment]
So it's not problem, right?

**Comment by monkeyDluffy6017** [comment]
I will close this issue, feel free to reopen it
