### ISSUE TITLE
help request: how to  add more vm configurations for  the java plugin

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/apisix-java-plugin-runner#281]
### Description

Dear,
I want to add more  vm configuration(--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED) for the cmd, but does not work.
**ext-plugin:
  cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/path/to/apisix-runner-bin/apisix-java-plugin-runner.jar']**

I tried the 2 ways , both don't work. Is there anyway to add vm configurations?
  cmd: ['/jdk17/bin/java', '--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED',  '-jar', '-Xmx1g', '-Xms1g', '/path/to/dubbo-plugin-0.0.1-SNAPSHOT.jar'] # d

  cmd: ['/jdk17/bin/java', '--add-opens java.base/java.lang=ALL-UNNAMED', '--add-opens java.base/java.math=ALL-UNNAMED', '--add-opens java.base/java.util=ALL-UNNAMED', '--add-opens java.base/java.lang.reflect=ALL-UNNAMED',  '-jar', '-Xmx1g', '-Xms1g', '/path/to/dubbo-plugin-0.0.1-SNAPSHOT.jar']

<img width="1706" alt="image" src="https://github.com/apache/apisix/assets/22955377/cf714350-5ba6-4989-bebf-eb7845b1a4c5">

### Environment

- APISIX version (run `apisix version`):3.7.0
- Operating system (run `uname -a`):linux centos 7

**Comment by mayunSaicmotor** [comment]
Dear  shreemaan-abhishek，could you help me？

**Comment by mayunSaicmotor** [comment]
Dear @shreemaan-abhishek ，could you help me？

**Comment by mayunSaicmotor** [comment]
Dear  @lakshya8066 could you help me？ Recently I am writing java plugin demo, but  blocked by this issue.I can't move forward anymore.

**Comment by lakshya8066** [comment]
Hi @mayunSaicmotor I still doing a deep dive into the issues here. Not sure if I can help soon enough.

**Comment by mayunSaicmotor** [comment]
Dear @lakshya8066 ,is there any update?

**Comment by mayunSaicmotor** [comment]
remove all whitespace and it ok now
`  cmd: ['/jdk17/bin/java',  '--add-opens',  'java.base/java.lang=ALL-UNNAMED',  '--add-opens',  'java.base/java.math=ALL-UNNAMED',  '--add-opens',  'java.base/java.util=ALL-UNNAMED',  '--add-opens',  'java.base/java.lang.reflect=ALL-UNNAMED',  '-jar', '/path/to/dubbo-plugin-0.0.1-SNAPSHOT-exec.jar']`
