### ISSUE TITLE
request help: receive undefined filter: XXX, skip it

### ISSUE THREAD

**Issue by yijieshusheng-git** [apache/apisix-java-plugin-runner#288]
### Issue description
Custom plugin launched successfully in Apisix, but filter display error when call it：
error log:
![image](https://github.com/apache/apisix-java-plugin-runner/assets/63898085/f37d023b-f22b-489d-b52a-b097f23eaf2f)

this is my jar details:
![image](https://github.com/apache/apisix-java-plugin-runner/assets/63898085/e875b720-6c41-4d92-bdd2-783f808a26f6)

### Environment
apisix   3.6.0

* your apisix-java-plugin-runner version
0.4.0

**Comment by tixbay-net** [comment]
Check the annotation of class LxwTestPlugin. '@Component' should be included.

**Comment by yijieshusheng-git** [comment]
> Check the annotation of class LxwTestPlugin. '@component' should be included.

ok thanks!
