### ISSUE TITLE
docs: Development link from External Plugins documentations 404

### ISSUE THREAD

**Issue by angolding** [apache/apisix-java-plugin-runner#303]
### Current State

**Description of the current state/issue**:
The link to plugin development documentation 404s

**Link to the page**:
from `https://apisix.apache.org/docs/java-plugin-runner/installation-guide/`:
```
<p>You can refer to <a target="_blank" href="/docs/java-plugin-runner/installation-guide/development.md/">development</a> to learn how to write custom plugins.</p>
```

**Screenshots (if relevant)**:
url navigated to: https://apisix.apache.org/docs/java-plugin-runner/installation-guide/development.md/

### Desired State

**Description of the change you are proposing**:
Development documentation link links to development document

### Would you like to fix this issue?

None

**Comment by yzeng25** [comment]
@angolding this change will show with the next release.
