### ISSUE TITLE
Can I port Zuul to apisix using this plugin?

### ISSUE THREAD

**Issue by freecache** [apache/apisix-java-plugin-runner#47]
Hi, 
   our gateway is Zuul2 and we implemented customized authentication and unified user session validation in it . As a result, it depends on some encryption and Redis libraries.  And now we would like to try APISIX and don not want to implement using another language. So can java plugin help us out?

**Comment by tzssangglass** [comment]
yes, that's what the java plugin is for.

**Comment by tzssangglass** [comment]
if you need some help, connect me.

**Comment by freecache** [comment]
> if you need some help, connect me.

OK. That's great. We will try out.
