### ISSUE TITLE
bug:  Chinese disorderly code

### ISSUE THREAD

**Issue by cyb331** [apache/apisix-java-plugin-runner#52]
### Issue description
Chinese disorderly code
### Environment

* your apisix-java-plugin-runner version
0.1.0
### Minimal test code / Steps to reproduce the issue
response.setStatusCode(503);
response.setHeader("Content-Encoding","UTF-8");
response.setHeader("Content-Type","application/json;charset=UTF-8");
response.setHeader("X-GATEWAY-ERROR-FLAG","error");
response.setBody("错误!!!,aaa");

### What's the actual result? (including assertion message & call stack if applicable)
??!!!,aaa
### What's the expected result?
错误!!!,aaa

**Comment by tzssangglass** [comment]
solve by #53
