### ISSUE TITLE
request help: How can i modify the request body with java plugin?

### ISSUE THREAD

**Issue by lcssos** [apache/apisix-java-plugin-runner#57]
### Issue description
How can i modify the request body with java plugin?

### Environment

* your apisix-java-plugin-runner version : 0.1.0

**Comment by tzssangglass** [comment]
not support yet, have a plan to support this.

**Comment by forget99** [comment]
> 
apisix-java-plugin-runner version : 0.4.0，does this version support modifying the request body?

**Comment by forget99** [comment]
> not support yet, have a plan to support this.

@tzssangglass apisix-java-plugin-runner version : 0.4.0，does this version support modifying the request body?
