### ISSUE TITLE
After the Java plugin is written and run, how does Apisix get the custom filter? Is it through the Spring container  

### ISSUE THREAD

**Issue by Rdebu** [apache/apisix-java-plugin-runner#58]
### Issue description
After the Java plugin is written and run, how does Apisix get the custom filter? Is it through the Spring container  
### Environment
apisix 2.7
apisix-java-plugin-runner 0.1
* your apisix-java-plugin-runner version
I want to know:
After the Java plugin is written and run, how does Apisix get the custom filter? Is it through the Spring ApplicationContext?

I want to get the Filter Bean "TokenValidator" by code . So when apisix is running, I send the request filtered by the TokenValidator immediately . We can see the filter TokenValidator was running. But I can't get the TokenValidator Bean from the Spring applicationContext . why?  Is it because it's not in the spring applicationContext?

the java code :  after apisix running for 15 seconds

![image](https://user-images.githubusercontent.com/58921097/129432465-ad2e753e-15f5-4ec7-8b3c-c0978031574c.png)

 (During this time I send a request from curl,can proved that the filter TokenValidator worked) ,

![image](https://user-images.githubusercontent.com/58921097/129432709-3c74bd8c-0417-4ee1-a66e-dbf0f83fedf5.png)

 I just tried to get the bean from spring applicationContext, but it turned out not to exist.

![image](https://user-images.githubusercontent.com/58921097/129432732-6b7d70bd-7dad-4999-acc1-e62d8a549356.png)

**Comment by tzssangglass** [comment]
yes, it's not in Spring container. see: https://github.com/apache/apisix-java-plugin-runner/blob/5a6c83709085527702dfc428117c2ae87f230d31/runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/A6HandlerConfiguration.java#L47-L53

requires the cache id to be fetched from the cache， and this cache is stored in APISIX.

**Comment by Rdebu** [comment]
> yes, it's not in Spring container. see:
> 
> https://github.com/apache/apisix-java-plugin-runner/blob/5a6c83709085527702dfc428117c2ae87f230d31/runner-core/src/main/java/org/apache/apisix/plugin/runner/handler/A6HandlerConfiguration.java#L47-L53
> 
> requires the cache id to be fetched from the cache， and this cache is stored in APISIX.

I want to get the Filter Bean by java code while Apisix is running .
![image](https://user-images.githubusercontent.com/58921097/129501592-5521b265-81ab-4c61-82b5-8e3c76e0b5b4.png)

but i tell me is null
![image](https://user-images.githubusercontent.com/58921097/129501654-057d8f80-c1d2-4227-b68a-7e9b9f57d88f.png)

how can i get the filter bean

**Comment by tzssangglass** [comment]
You could find a way to release the `filterMap` from inside the object, but I don't recommend it and I haven't tried it.

**Comment by Rdebu** [comment]
> You could find a way to release the `filterMap` from inside the object, but I don't recommend it and I haven't tried it.

yes , i did it.
![image](https://user-images.githubusercontent.com/58921097/129502500-64dcd7e3-777f-4e30-80fb-67fd4cb33fcc.png)
But he seems to be empty

**Comment by Rdebu** [comment]
> You could find a way to release the `filterMap` from inside the object, but I don't recommend it and I haven't tried it.

i want get the A6ConfigHandler Bean by spring @Autowired
![image](https://user-images.githubusercontent.com/58921097/129502959-7936dbda-68d0-4c70-bc9c-0562835c38d4.png)

but it tell me it is null
![image](https://user-images.githubusercontent.com/58921097/129502999-572b7c75-7469-4e5e-baa6-4987fa157f51.png)

![image](https://user-images.githubusercontent.com/58921097/129503026-fe5f7aca-b804-4e5e-ab8e-5314108ea5df.png)

**Comment by Rdebu** [comment]
> You could find a way to release the `filterMap` from inside the object, but I don't recommend it and I haven't tried it.

i find my error. thx
