### ISSUE TITLE
java.lang.IllegalStateException: Failed to execute CommandLineRunner

### ISSUE THREAD

**Issue by Hireek** [apache/apisix-java-plugin-runner#65]
Caused by: reactor.netty.ChannelBindException: Failed to bind on [/tmp/runner.sock]

how can i config APISIX_LISTEN_ADDRESS?

**Comment by Hireek** [comment]
Caused by: java.lang.IllegalArgumentException: Unsupported channel type: ServerDomainSocketChannel

**Comment by arabot777** [comment]
hello, I have encountered the same problem, how did you solve it?

**Comment by RagavMaddali** [comment]
do we have a way to resolve the issue

**Comment by arabot777** [comment]
> 
1. if you use mac m1, please import the aarch64 version of the netty-transport-native-kqueue package
2. in other cases, please check the permissions of the runner.sock file,

**Comment by RagavMaddali** [comment]
> if you use mac m1, please import the aarch64 version of the netty-transport-native-kqueue package
> in other cases, please check the permissions of the runner.sock file,

On the run mode the file is created dynamically. I tried running the process with both sudo and as as root user.
