### ISSUE TITLE
Start apisix with docker-compose, write the plugin in java and find that apisix does not create a runner.sock How do I generate a runner.sock?

### ISSUE THREAD

**Issue by jmxzzz** [apache/apisix-java-plugin-runner#69]
### Environment

* your apisix-java-plugin-runner version

**Comment by bzp2010** [comment]
Please refer to this document, [**link here**](https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/how-it-works.md)

**Comment by tzssangglass** [comment]
The doc already show, feel free to reopen it.
