### ISSUE TITLE
request help: get the parameters in the post body

### ISSUE THREAD

**Issue by SireHan** [apache/apisix-java-plugin-runner#71]
### Issue description
我该如何拿到 请求body 做自己的处理，我从Req对象里面没有看到 request body
因为post请求 我需要拿到post body里面的参数做自己的处理

### Environment

* your apisix-java-plugin-runner 0.1.0

**Comment by tzssangglass** [comment]
not support for post body

**Comment by qinming99** [comment]
> 不支持帖子正文



> not support for post body

The Java plug-in can get the body function from the request. Is there any plan? When can I get the body from the request

**Comment by tzssangglass** [comment]
has support by new release.
