### ISSUE TITLE
feature: java plugin log path error

### ISSUE THREAD

**Issue by qinming99** [apache/apisix-java-plugin-runner#75]
The log of the Java plug-in is written to the error.log of apisix, which is unreasonable. Because the plug-in itself will generate many logs, the plug-in log is mixed with the apisix log

advice：
The Java plug-in log is printed separately and controlled by the Java plug-in itself

**Comment by qinming99** [comment]
This function should need to be changed apisix ?

**Comment by tzssangglass** [comment]
> This function should need to be changed apisix ?

yes

**Comment by laizuan** [comment]
how do I send logs to the rocketmq-logger plug-in ?

**Comment by tzssangglass** [comment]
> how do I send logs to the rocketmq-logger plug-in ?

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/rocketmq-logger.md

BTW, your question is not related to the current issue.

**Comment by tzssangglass** [comment]
same as #22
