### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by yunfhu** [apache/apisix-java-plugin-runner#76]
### Issue description
After deep researched on Apache apisix,I have a question about the Java plug-in runner,is it able to support none http protocol?or is able to support private protocol which is implemented over tcp/ip ?The java plugin runner used netty as network frontend,neety should support private protocol which is implemented over tcp/ip.what i want to do is implement a plugin which is similar to MQTT-PROXY,but a self defined protocol implemented over tcp/ip,After apisix received the request, forward request to java plugin, then i can decode it, forward it to other service or deal with any other business logic in the plugin
### Environment

* your apisix-java-plugin-runner version

**Comment by tzssangglass** [comment]
If you read the code, you will see that apisix uses the tcp/ip private protocol with the java plugin runner.
see: https://github.com/apache/apisix-java-plugin-runner/blob/a5ca9ca8045a19694b94c57986ae7d298eff986e/runner-core/src/main/java/org/apache/apisix/plugin/runner/codec/DelayedDecoder.java#L25

for the definition of private protocols, you can refer to:https://lists.apache.org/thread.html/r7524b2622fbdf152a83b48e8c9d680075fbe64cb0f3591e0bf3212e9%40%3Cdev.apisix.apache.org%3E
