### ISSUE TITLE
failed to receive RPC_PREPARE_CONF: timeout

### ISSUE THREAD

**Issue by ColdFragrance** [apache/apisix-java-plugin-runner#77]
### Issue description
Hi,everyone.According to steps of https://apisix.apache.org/zh/blog/2021/06/21/use-Java-to-write-Apache-APISIX-plugins/，I start java-plugin program and apisix，apisix's log show errors as below:

2021/10/14 19:43:55 [error] 4648#4648: *20111 [lua] init.lua:617: phase_func(): failed to receive RPC_PREPARE_CONF: timeout, client: 127.0.0.1, server: _, request: "GET /get HTTP/1.1", host: "127.0.0.1:9080"
2021/10/14 19:43:55 [warn] 4648#4648: *20111 [lua] plugin.lua:680: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 127.0.0.1, server: _, request: "GET /get HTTP/1.1", host: "127.0.0.1:9080"

And description by https://github.com/apache/apisix-java-plugin-runner/blob/release/0.1/docs/en/latest/development.md,I got the same error.

Who can help me？Thanks.

### Environment
Dev Environment: CentOS7.4+Eclipse4.21+JDK8+apisix-java-plugin-runner-0.1.0+apisix2.10.0
* your apisix-java-plugin-runner version
apisix-java-plugin-runner-0.1.0

**Comment by tzssangglass** [comment]
And you can use the master branch to test.

It looks like the java plugin runner has received the request form APISIX.

> 2021-10-15 19:43:47.292 DEBUG 14813 --- [tor-tcp-epoll-3] i.n.h.l.LoggingHandler : [id: 0x0f2c7754] INACTIVE
> 2021-10-15 19:43:47.292 DEBUG 14813 --- [tor-tcp-epoll-3] r.n.c.FluxReceive : [id:0f2c7754] FluxReceive{pending=0, cancelled=true, inboundDone=false, inboundError=null}: dropping frame PooledSlicedByteBuf(ridx: 0, widx: 116, cap: 116/116, unwrapped: PooledUnsafeDirectByteBuf(ridx: 116, widx: 116, cap: 2048))
> 2021-10-15 19:43:47.292 DEBUG 14813 --- [tor-tcp-epoll-3] i.n.h.l.LoggingHandler : [id: 0x0f2c7754] UNREGISTERED

see if there are any problems with these logs.

And did you break the point in the java plugin code?

**Comment by ColdFragrance** [comment]
I used the master branch.and no breakpoint all the time.

**Comment by ColdFragrance** [comment]
My plugin's code as below:
package org.apache.apisix.plugin.runner.filter;

import java.util.logging.Logger;

import org.apache.apisix.plugin.runner.HttpRequest;
import org.apache.apisix.plugin.runner.HttpResponse;
import org.springframework.stereotype.Component;

import reactor.core.publisher.Mono;

@Component
public class FooFilter implements PluginFilter {

    private static final Logger log4j = Logger.getLogger("FooFilter");

    @Override
    public String name() {
        log4j.info("FooFilter");
        return "FooFilter";
    }

    @Override
    public Mono<Void> filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) {
        log4j.info("FooFilter filter");
        return chain.filter(request, response);
    }
}

Additionally, my test via curl is normal when non-java-plugin.

**Comment by tzssangglass** [comment]
Maybe you can try run mode:https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/how-it-works.md#run

**Comment by tzssangglass** [comment]
no more response, considered as resolved, feel free to reopen this.

**Comment by jiuchongxiao** [comment]
@ColdFragrance do you solved it ,how to solved? i have the same issue

**Comment by ennian001** [comment]
> no more response, considered as resolved, feel free to reopen this.
@ColdFragrance 
do you solved it ,how to solved? i have the same issue

**Comment by 1075924135** [comment]
1.8不支持0.4.0中的语法，linux上把jdk替换成11执行，问题解决
