### ISSUE TITLE
bug: socket type file permissions not set accurately after apisix-java-plugin-runner automatically create this file when it starts

### ISSUE THREAD

**Issue by BlackEragon** [apache/apisix-java-plugin-runner#78]
### Issue description
socket type file permissions not set accurately after apisix-java-plugin-runner automatically create this file when it starts，Why not set the file permissions after automatically create in the code？
like：
···
        logger.warn("java runner is listening on the socket file: {}", socketFile);
        Runtime.getRuntime().exec("chmod 766 " + socketFile);
···

### Environment

* your apisix-java-plugin-runner version

### What's the actual result? (including assertion message & call stack if applicable)

phase_func(): failed to connect to the unix socket unix:/tmp/runner.sock: permission denied

### What's the expected result?

This will not need to manually execute the command in docker.

**Comment by NUPT-Pig** [comment]
I have the same problem while running apisix in docker
I seems default Permission is not “766” under folder /usr/local/apisix/conf/
----------------------------------------
2021/11/01 11:04:45 [crit] 49#49: *14544 connect() to unix:/usr/local/apisix/conf/apisix-46.sock failed (13: Permission denied), client: 172.19.0.1, server: _, request: "GET /mdr_backend/msp/dashboard/ioa_company_info?insight_user=admin@msp&during_type=2 HTTP/1.1", host: "localhost:9080"

**Comment by cws1981** [comment]
this is my Dockerfile:
```
FROM apache/apisix:2.10.0-alpine

RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories && apk add --no-cache openjdk11-jre-headless

ADD apisix-java-plugin-runner.jar /usr/local/apisix-java-plugin-runner.jar
```
i rebuild docker images add apisix-java-plugin-runner.jar, so the java-plugin will in the same container with apisix, but when it still outputs errors in the error.log:
```
2021/11/25 06:33:31 [crit] 44#44: *2280 connect() to unix:/usr/local/apisix/conf/apisix-1.sock failed (13: Permission denied)
```

this is the processes in the container:
```
PID   USER     TIME  COMMAND
    1 root      0:00 {openresty} nginx: master process /usr/local/openresty/bin/openresty -p /usr/local/apisix -g daemon off;
   44 nobody    0:00 {openresty} nginx: worker process
   45 nobody    0:00 {openresty} nginx: worker process
   46 nobody    0:00 {openresty} nginx: worker process
   47 nobody    0:00 {openresty} nginx: worker process
   48 nobody    0:00 {openresty} nginx: cache manager process
   49 nobody    0:00 {openresty} nginx: cache loader process
   50 root      0:00 {openresty} nginx: privileged agent process
   56 root      0:15 java -jar -Xmx4g -Xms4g /usr/local/apisix-runner-bin/apisix-java-plugin-runner.jar
```

**Comment by cws1981** [comment]
> 1. on debug mode, the socket file is generated by Java plugin runner;
> 2. on run mode, the socket file is generated by APISXI, so we don't need to set the file permissions by code, otherwise this code will cause an exception in run mode.

apisix worker process user is nobody no Permission

**Comment by cws1981** [comment]
> 

```java
Runtime.getRuntime().exec("chmod 777 " + socketFile);
```
this is work for me.

**Comment by tzssangglass** [comment]
> 我在 docker 中通过 docker-compose 运行 APISXI，在运行模式下，仍然出现权限被拒绝

see: https://github.com/apache/apisix/discussions/5628#discussioncomment-1713241

**Comment by geekgao** [comment]
这个问题我们也遇到了，排查半天，感觉太诡异了，应该设置为noboy才合理吧 ;(

**Comment by tzssangglass** [comment]
> 这个问题我们也遇到了，排查半天，感觉太诡异了，socket权限应该设置为noboy才合理吧 ;(

yes, PR is wolcome.

**Comment by tzssangglass** [comment]
considered as resolved, feel free to reopen this.

ref to: https://github.com/apache/apisix-java-plugin-runner/blob/cbd3b3a6ad536df5d1ea71336c4a319a28c0622d/runner-core/src/main/java/org/apache/apisix/plugin/runner/server/ApplicationRunner.java#L109
