### ISSUE TITLE
request help: How do I get my Java custom plug-in to take precedence over the VARS feature

### ISSUE THREAD

**Issue by Rdebu** [apache/apisix-java-plugin-runner#84]
### Issue description

How do I get my Java custom plug-in to take precedence over the VARS feature
【如何让我的java自定义插件优先于vars功能】
I want to add a new parameter SID to the request based on the RID parameter, and then customize the publication based on the SID parameter.
【我想要在请求中根据rid参数添加一个新参数sid，再根据sid参数进行自定义发布。】
The problem is that vars take precedence over ext-plugin-pre-req  
【但是现在碰到的问题是vars优先于ext-plugin-pre-req 执行】
Is there any way to make ext-plugin-pre-req run first?
【有什么办法能让ext-plugin-pre-req 先执行呢？】

### Environment

* your apisix-java-plugin-runner version
0.1

**Comment by tzssangglass** [comment]
1. apisix-java-runner doesn't support to read and rewrite request body yet, just can read and rewrite request args.
2. if you want ro rewrite request args by apisix-java-plugin-runner, an you try to config `ext-plugin-*` plugin on global rule of APISIX? global rule plugins run before route match.

**Comment by tzssangglass** [comment]
apisix-java-runner 0.2.0 release support to read request body.

considered as resolved, feel free to reopen this.
