### ISSUE TITLE
bug: serverless-pre-function配置报错

### ISSUE THREAD

**Issue by sahara0506** [apache/apisix-java-plugin-runner#90]
使用高级玩法的时候，脚本提交的时候报错：
脚本配置：
"serverless-pre-function": {
      "disable": false,
      "functions": [
        "local core = require('apisix.core')  core.response.exit(403) "
      ],
      "phase": "access"
    }

提交报错

2021/11/27 22:55:28 [error] 50#50: *229857 [lua] config_etcd.lua:569: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin serverless-pre-function err: pcall error: /usr/local/apisix/apisix/core/response.lua:56: API disabled in the current context,  etcd key: /apisix/routes, context: ngx.timer
2021/11/27 22:55:28 [error] 49#49: *230042 [lua] config_etcd.lua:569: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin serverless-pre-function err: pcall error: /usr/local/apisix/apisix/core/response.lua:56: API disabled in the current context,  etcd key: /apisix/routes, context: ngx.timer
2021/11/27 22:55:28 [error] 48#48: *230106 [lua] config_etcd.lua:569: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin serverless-pre-function err: pcall error: /usr/local/apisix/apisix/core/response.lua:56: API disabled in the current context,  etcd key: /apisix/routes, context: ngx.timer
2021/11/27 22:55:28 [error] 53#53: *230468 [lua] config_etcd.lua:569: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin serverless-pre-function err: pcall error: /usr/local/apisix/apisix/core/response.lua:56: API disabled in the current context,  etcd key: /apisix/routes, context: ngx.timer
2021/11/27 22:55:28 [error] 47#47: *229646 [lua] config_etcd.lua:569: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin serverless-pre-function err: pcall error: /usr/local/apisix/apisix/core/response.lua:56: API disabled in the current context,  etcd key: /apisix/routes, context: ngx.timer

**Comment by tzssangglass** [comment]
This error is not related to this project.

pls go to the APISIX project and submit an issue with a replication example.
