### ISSUE TITLE
request help: when reload apisix, the java service will be reload too, and during this period, it is not available.

### ISSUE THREAD

**Issue by arabot777** [apache/apisix-java-plugin-runner#91]
### Issue description
when reload apisix, the java service will be reload too, and during this period, apisix is not available（return 503）.
Is there a better solution? running java service in debugger?

**Comment by tzssangglass** [comment]
> Is there a better solution

The processes of the runner are governed by apisix on runtime, so what is the better solution?

**Comment by arabot777** [comment]
After our test, the performance loss of the two deployment methods is almost the same.
From a product point of view, the two should indeed be a whole. But from a deployment perspective, the startup speed of the `java plugins` **seriously slows down** the apisix service. 
Considering that the deployment frequency of java plugins is low, and the operation frequency of apisix `reload` is high. We use `systemd` to keep the service alive.

**Comment by tzssangglass** [comment]
We currently propose to host the lifecycle of the java runner by APISIX.

**Comment by tzssangglass** [comment]
@arabot777  can we close this issue now?

**Comment by arabot777** [comment]
Okay, we will discuss it internally. grateful.
