### ISSUE TITLE
request help: How to get all the information in the original request header.

### ISSUE THREAD

**Issue by tiankanghello** [apache/apisix-java-plugin-runner#92]
What can I do to get all the information in the original request header, including the host and URI of the request, and the query parameter in the URI. ApiSix doesn't seem to have a good example of how to get the content in the original request

**Comment by tzssangglass** [comment]
here: https://github.com/apache/apisix-java-plugin-runner/blob/1a682617a12a2350370f9bf5d6daa3f0bf11f099/runner-plugin-sdk/src/main/java/org/apache/apisix/plugin/runner/HttpRequest.java#L141-L150

maybe rename this function to `getHeaders` is better, would you like to submit a PR to fix it and add more use cases?

**Comment by 123liubao** [comment]
@tzssangglass  Hello, I want to fix this issue, could you please assign it to me.

**Comment by yongxianggeng** [comment]
请问一下，你这个问题解决了吗？我这边测试也是从client request拿不到对应的请求头信息

**Comment by tzssangglass** [comment]
> 请问一下，你这个问题解决了吗？我这边测试也是从client request拿不到对应的请求头信息

See the response above, or provide the full reproduction of the steps.
