### ISSUE TITLE
request help: can i rewrite the proxy response with java-plugin-runner

### ISSUE THREAD

**Issue by SireHan** [apache/apisix-java-plugin-runner#94]
### Issue description
我想对apisix 代理的响应结果进行修改，但是apisix body-filter不能通过rpc调用发送结果给 java-plugin-runner
API disabled in the context of body_filter_by_lua* 
我对lua脚本不是很熟悉，更改response更擅长用java
### Environment
apisix 2.10
* your apisix-java-plugin-runner version
java-plugin-runner 0.1

**Comment by tzssangglass** [comment]
> 我想对apisix 代理的响应结果进行修改

you can use `response-rewrite` plugin in APISIX.

> API disabled in the context of body_filter_by_lua*

this is limit of  openresty

**Comment by tzssangglass** [comment]
considered as resolved, feel free to reopen this.
